<link rel="stylesheet" href="{{ asset('website/assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/fontawesome.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/swiper.min.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/odometer.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/jquery-ui.min.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('website/assets/css/main.css') }}">
