<!-- jquery include -->
<script src="{{ asset('website/assets/js/jquery-3.7.1.min.js') }}"></script>
<script src="{{ asset('website/assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('website/assets/js/swiper.min.js') }}"></script>
<script src="{{ asset('website/assets/js/wow.min.js') }}"></script>
<script src="{{ asset('website/assets/js/appear.js') }}"></script>
<script src="{{ asset('website/assets/js/odometer.min.js') }}"></script>
<script src="{{ asset('website/assets/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('website/assets/js/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset('website/assets/js/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('website/assets/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('website/assets/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('website/assets/js/parallax-scroll.js') }}"></script>
<script src="{{ asset('website/assets/js/main.js') }}"></script>
